# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIcCbN2FqxkDWQL8xEDEupa8DMDoiHxP
"""

import pandas as pd

file_path = '/content/delivery_data.csv.xlsx'
df = pd.read_excel(file_path)

display(df.head())

print(df.info())
print(df.describe())

df_processed = df.drop('ID', axis=1)
df_processed = pd.get_dummies(df_processed, columns=['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender'], drop_first=True)

X = df_processed.drop('Reached.on.Time_Y.N', axis=1)
y = df_processed['Reached.on.Time_Y.N']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns

# Initialize and train the Logistic Regression model
log_reg_model = LogisticRegression(solver='liblinear', random_state=42)
log_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = log_reg_model.predict(X_test)
y_pred_proba = log_reg_model.predict_proba(X_test)[:, 1]

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Not on Time', 'On Time'], yticklabels=['Not on Time', 'On Time'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Classification Report (Precision, Recall, F1-score)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ROC Curve and AUC
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
auc = roc_auc_score(y_test, y_pred_proba)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='blue', label=f'ROC Curve (AUC = {auc:.2f})')
plt.plot([0, 1], [0, 1], color='red', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.grid(True)
plt.show()

print(f"Area Under the Curve (AUC): {auc:.2f}")

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Initialize and train the Linear Regression model
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_linear = lin_reg_model.predict(X_test)

# Calculate R-squared
r_squared = r2_score(y_test, y_pred_linear)

print(f"R-squared for Linear Regression: {r_squared:.2f}")

# Optionally, you can also print coefficients to see feature importance
# print("\nLinear Regression Coefficients:")
# for feature, coef in zip(X.columns, lin_reg_model.coef_):
#     print(f"{feature}: {coef:.4f}")

"""### Building and Deploying a Predictive Tool

First, we'll save our best performing model (Logistic Regression) for later use. Then, we will create a function that takes raw input, preprocesses it, and uses the saved model to make a prediction.
"""

import joblib

# Save the Logistic Regression model
model_filename = 'logistic_regression_model.joblib'
joblib.dump(log_reg_model, model_filename)

print(f"Logistic Regression model saved as '{model_filename}'")

"""Now, let's create a prediction function. This function will take new, raw data as input, apply the same preprocessing steps (one-hot encoding) that we used for training, and then use the loaded model to make a prediction."""

import pandas as pd
import joblib

def predict_delivery_on_time(new_data_row, trained_columns, model_path='logistic_regression_model.joblib'):
    """
    Predicts whether a delivery will be on time using the trained Logistic Regression model.

    Args:
        new_data_row (dict): A dictionary representing a single row of new data.
                             Keys should match original column names before one-hot encoding.
        trained_columns (list): A list of column names (features) that the model was trained on.
        model_path (str): Path to the saved model file.

    Returns:
        int: 1 if predicted to be on time, 0 otherwise.
    """
    # Load the model
    model = joblib.load(model_path)

    # Convert the new data row to a DataFrame
    new_df = pd.DataFrame([new_data_row])

    # Apply one-hot encoding to categorical features (matching training process)
    categorical_cols = ['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']
    new_df_processed = pd.get_dummies(new_df, columns=categorical_cols, drop_first=True)

    # Ensure all columns from training are present and in the correct order
    # Add missing columns with 0 and reorder
    for col in trained_columns:
        if col not in new_df_processed.columns:
            new_df_processed[col] = 0
    new_df_processed = new_df_processed[trained_columns]

    # Make prediction
    prediction = model.predict(new_df_processed)

    return prediction[0]

# Example usage:
# First, we need the list of columns the model was trained on (X_train.columns)
feature_columns = X_train.columns.tolist()

# Create a sample new data point (without 'ID' and 'Reached.on.Time_Y.N')
sample_new_data = {
    'Cost_of_the_Product': 250,
    'Prior_purchases': 3,
    'Discount_offered': 5,
    'Weight_in_gms': 3000,
    'Warehouse_block': 'B',
    'Mode_of_Shipment': 'Flight',
    'Product_importance': 'low',
    'Gender': 'F'
}

predicted_status = predict_delivery_on_time(sample_new_data, feature_columns)

if predicted_status == 1:
    print(f"Predicted delivery status: On Time")
else:
    print(f"Predicted delivery status: Not on Time")

# Another example
sample_new_data_2 = {
    'Cost_of_the_Product': 100,
    'Prior_purchases': 2,
    'Discount_offered': 20,
    'Weight_in_gms': 5000,
    'Warehouse_block': 'A',
    'Mode_of_Shipment': 'Ship',
    'Product_importance': 'high',
    'Gender': 'M'
}

predicted_status_2 = predict_delivery_on_time(sample_new_data_2, feature_columns)

if predicted_status_2 == 1:
    print(f"Predicted delivery status (Example 2): On Time")
else:
    print(f"Predicted delivery status (Example 2): Not on Time")

# Save the Logistic Regression model in .sav format
model_filename_sav = 'logistic_regression_model.sav'
joblib.dump(log_reg_model, model_filename_sav)

print(f"Logistic Regression model saved as '{model_filename_sav}'")

"""Next, here is the content for your Streamlit application. You should copy this code, save it as a Python file (e.g., `delivery_predictor.py`), and then run it from your terminal using `streamlit run delivery_predictor.py`. Make sure you have `streamlit`, `pandas`, and `scikit-learn` installed (`pip install streamlit pandas scikit-learn joblib`).

This app will allow managers to input delivery details and get a prediction of whether the delivery will be on time. This can serve as the basis for your user study tool.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile delivery_predictor.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load the trained model and feature columns
# # Ensure the model file is in the same directory as this script or provide the full path
# model = joblib.load('logistic_regression_model.sav')
# 
# # Define the feature columns used during training (X_train.columns from your notebook)
# # This list must exactly match the columns used to train the model, including the order
# # You might need to manually copy this from your notebook's X_train.columns.tolist()
# feature_columns = ['Cost_of_the_Product', 'Prior_purchases', 'Discount_offered', 'Weight_in_gms',
#                    'Warehouse_block_B', 'Warehouse_block_C', 'Warehouse_block_D', 'Warehouse_block_F',
#                    'Mode_of_Shipment_Road', 'Mode_of_Shipment_Ship',
#                    'Product_importance_low', 'Product_importance_medium', 'Gender_M']
# 
# st.set_page_config(page_title="Delivery On-Time Predictor", layout="centered")
# st.title("🚚 Delivery On-Time Predictor")
# st.markdown("Enter the details of the delivery to predict if it will arrive on time.")
# 
# # Input fields for user
# st.header("Delivery Details")
# 
# c_cost = st.number_input("Cost of the Product", min_value=50, max_value=500, value=200)
# c_prior = st.number_input("Number of Prior Purchases", min_value=0, max_value=10, value=3)
# c_discount = st.number_input("Discount Offered", min_value=0, max_value=70, value=10)
# c_weight = st.number_input("Weight in Grams", min_value=100, max_value=8000, value=3000)
# 
# warehouse_block_options = ['A', 'B', 'C', 'D', 'F']
# c_warehouse = st.selectbox("Warehouse Block", warehouse_block_options)
# 
# shipment_mode_options = ['Flight', 'Road', 'Ship']
# c_shipment = st.selectbox("Mode of Shipment", shipment_mode_options)
# 
# product_importance_options = ['low', 'medium', 'high']
# c_product_importance = st.selectbox("Product Importance", product_importance_options)
# 
# c_gender = st.radio("Gender of Customer", ['M', 'F'])
# 
# if st.button("Predict Delivery Status"):
#     # Create a DataFrame from the inputs, matching the original dataframe structure for preprocessing
#     input_df = pd.DataFrame([{
#         'Cost_of_the_Product': c_cost,
#         'Prior_purchases': c_prior,
#         'Discount_offered': c_discount,
#         'Weight_in_gms': c_weight,
#         'Warehouse_block': c_warehouse,
#         'Mode_of_Shipment': c_shipment,
#         'Product_importance': c_product_importance,
#         'Gender': c_gender
#     }])
# 
#     # Apply one-hot encoding, matching training process
#     categorical_cols = ['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']
#     input_df_processed = pd.get_dummies(input_df, columns=categorical_cols, drop_first=True)
# 
#     # Ensure all feature columns from training are present and in the correct order
#     final_input = pd.DataFrame(columns=feature_columns) # Create an empty DF with all expected columns
#     for col in feature_columns:
#         if col in input_df_processed.columns:
#             final_input[col] = input_df_processed[col]
#         else:
#             final_input[col] = 0 # Add missing columns as 0 (for one-hot encoded cols not present)
# 
#     # Make prediction
#     prediction = model.predict(final_input)
#     prediction_proba = model.predict_proba(final_input)[:, 1]
# 
#     st.subheader("Prediction Result:")
#     if prediction[0] == 1:
#         st.success(f"The delivery is predicted to be **On Time**! (Probability: {prediction_proba[0]:.2f})")
#     else:
#         st.error(f"The delivery is predicted to be **Not On Time**. (Probability: {prediction_proba[0]:.2f})")
# 
#     st.markdown("--- ")
#     st.info("This prediction is based on a Logistic Regression model trained on historical delivery data.")
#

"""### Conceptual Deployment of the Predictive Tool

To "deploy" this as a predictive tool for managers or users, you would typically:

1.  **Create a User Interface (UI):** This could be a simple web application (using frameworks like Flask or Django in Python), a desktop application, or even an interactive dashboard.
2.  **Input Collection:** The UI would allow users to input the relevant features for a new delivery (e.g., Cost of the Product, Prior Purchases, Warehouse Block, etc.).
3.  **Backend Processing:** When the user submits the input:
    *   The input data is formatted into a dictionary (like `sample_new_data` above).
    *   The `predict_delivery_on_time` function is called with this data and the saved model.
    *   The prediction result (0 or 1) is returned.
4.  **Display Result:** The UI displays the prediction to the user in an understandable format (e.g., "Predicted: On Time" or "Predicted: Not on Time").

This setup allows non-technical users to leverage the predictive model without needing to write or understand the underlying code. The next step, as you outlined, would be to conduct a managerial user study using this tool.
"""